version : ""
services:
  wisefee-database:
    platform: linux/x86_64
    image: mariadb:10.3.30
    environment:
      MARIADB_DATABASE: "test"
      MARIADB_ROOT_PASSWORD: "root"
    ports:
      - 3320
    volumes:
      - ./local-mariadb:/var/lib/docker/volumes